FROM node:22-alpine AS build
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

ARG VITE_API_BASE_URL_PROD=https://api.pariswestdrive.fr
ENV VITE_API_BASE_URL_PROD=${VITE_API_BASE_URL_PROD}

RUN npm run build

FROM nginx:1.27-alpine AS runtime
COPY docker/nginx.prod.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
